import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import { NotificationProvider, Notification } from "@/components/notification";
import OverlayTop from "@/components/overlay-top";
import OverlayLeft from "@/components/overlay-left";
import OverlayRight from "@/components/overlay-right";
import OverlayContent from "@/components/overlay-content";
import { OverlayProvider } from "@/hooks/useOverlay";

const robotoSans = Roboto({
  variable: "--font-roboto",
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable} antialiased`}>
        <NotificationProvider>
          <OverlayProvider>
            <OverlayContent>
              {children}
            </OverlayContent>
            <OverlayLeft />
            <OverlayRight />
            <OverlayTop />
            <Notification />
          </OverlayProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
