name: build-all

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  SERVICES: |
    auth-service
    gateway-service
    image-service
    notification-service
    web

jobs:
  build-all:
    name: Build All Services
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        service: [auth-service, gateway-service, image-service, notification-service, web]
      max-parallel: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "version=${TAG_NAME}" >> "$GITHUB_OUTPUT"
          echo "Tag: ${TAG_NAME}"

      - name: Compute Docker tags
        id: meta
        run: |
          REPO_NAME="${{ env.REGISTRY_USERNAME }}/instrlabs-${{ matrix.service }}"
          VERSION=${{ steps.version.outputs.version }}

          # Create tags: version and latest
          TAGS="${REPO_NAME}:${VERSION},${REPO_NAME}:latest"

          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"
          echo "Computed tags: ${TAGS}"

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image summary
        run: |
          echo "### Build Summary for ${{ matrix.service }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Service:** ${{ matrix.service }}" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Docker Repository:** ${{ env.REGISTRY_USERNAME }}/instrlabs-${{ matrix.service }}" >> $GITHUB_STEP_SUMMARY
          echo "**Tags:** ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: build-all
    if: always()

    steps:
      - name: Build complete
        run: |
          echo "✅ All services built successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Services built:**" >> $GITHUB_STEP_SUMMARY
          echo "- auth-service" >> $GITHUB_STEP_SUMMARY
          echo "- gateway-service" >> $GITHUB_STEP_SUMMARY
          echo "- image-service" >> $GITHUB_STEP_SUMMARY
          echo "- notification-service" >> $GITHUB_STEP_SUMMARY
          echo "- web" >> $GITHUB_STEP_SUMMARY
